name: Run in Container example
on:
  pull_request

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: node:18.10.0-buster
      env:
        NODE_ENV: development
      ports:
        - 8080
      options: --cpus 1
    steps:
